language: "perl"
perl:
    - "5.18"
#    - "5.16"
#    - "5.14"
    - "5.12"
#
before_install:
    - cpanm Test::More
    - cpanm Module::Install
    - cpanm Module::Install::AuthorTests
    - cpanm Module::Install::Repository

install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org . || cat ~/.cpanm/build.log

script: perl Makefile.PL && make test

after_failure: 
    - "cat ~/.cpanm/build.log"
