language: "perl"
perl:
    - "5.18"
    - "5.16"
      #- "5.14"
      #- "5.12"

before_install:
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: 
    - perl Makefile.PL
    - make test
